In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
# example of using ImageDataGenerator to standardize images
from keras.datasets import mnist
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Conv2D, Convolution2D
from keras.layers import Dense, Dropout, Activation, Flatten, Add, BatchNormalization
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.preprocessing.image import ImageDataGenerator
from keras import regularizers
from keras.callbacks import ModelCheckpoint, LearningRateScheduler
# load dataset
(trainX, trainY), (testX, testY) = mnist.load_data()
# reshape dataset to have a single channel
width, height, channels = trainX.shape[1], trainX.shape[2], 1
trainX = trainX.reshape((trainX.shape[0], width, height, channels))
testX = testX.reshape((testX.shape[0], width, height, channels))
trainX = trainX.astype('float32')
testX = testX.astype('float32')
trainX /= 255
testX /= 255
# one hot encode target values
trainY = to_categorical(trainY)
testY = to_categorical(testY)
# create generator to standardize images
datagen = ImageDataGenerator(featurewise_center=True, featurewise_std_normalization=True)
# calculate mean on training dataset
datagen.fit(trainX)
# prepare an iterators to scale images
train_iterator = datagen.flow(trainX, trainY, batch_size=512)
test_iterator = datagen.flow(testX, testY, batch_size=512)
print('Batches train=%d, test=%d' % (len(train_iterator), len(test_iterator)))


Using TensorFlow backend.


11493376/11490434 [==============================] - 2s 0us/step
Batches train=118, test=20


In [3]:
# define model
model = Sequential()

model.add(Convolution2D(10, 3, 3, kernel_regularizer=regularizers.l2(0.01), input_shape=(28,28,1))) # 26 3X3
model.add(BatchNormalization())
model.add(Activation('relu'))

model.add(Convolution2D(16, 3, 3, kernel_regularizer=regularizers.l2(0.01))) # 24 5X5
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Convolution2D(16, 3, 3 , kernel_regularizer=regularizers.l2(0.01))) # 22 7X7
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Convolution2D(10, 3, 3 , kernel_regularizer=regularizers.l2(0.01))) # 20 9X9
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Convolution2D(16, 3, 3 , kernel_regularizer=regularizers.l2(0.01))) # 18 11X11
model.add(BatchNormalization())
model.add(Activation('relu'))

model.add(Dropout(0.025))

model.add(MaxPooling2D(pool_size=(2, 2))) # 9 22X22
model.add(Convolution2D(10, 1, 1 , kernel_regularizer=regularizers.l2(0.01))) #  7 24X24
model.add(BatchNormalization())
model.add(Activation('relu'))

model.add(Convolution2D(16, 3, 3 , kernel_regularizer=regularizers.l2(0.01))) # 5 26X26
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Convolution2D(16, 3, 3 , kernel_regularizer=regularizers.l2(0.01))) #  3 28X28
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.025))


model.add(Convolution2D(16, 3, 3 , kernel_regularizer=regularizers.l2(0.01))) 
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Convolution2D(10, 1 , kernel_regularizer=regularizers.l2(0.01))) 
model.add(Activation('relu'))

model.add(Convolution2D(10, 3 , kernel_regularizer=regularizers.l2(0.01)))
model.add(Flatten())
model.add(Activation('softmax'))





Instructions for updating:
Colocations handled automatically by placer.


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(10, (3, 3), kernel_regularizer=<keras.reg..., input_shape=(28, 28, 1...)`
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(16, (3, 3), kernel_regularizer=<keras.reg...)`
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(16, (3, 3), kernel_regularizer=<keras.reg...)`
  # Remove the CWD from sys.path while we load stuff.


Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(10, (3, 3), kernel_regularizer=<keras.reg...)`
  del sys.path[0]
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(16, (3, 3), kernel_regularizer=<keras.reg...)`
  app.launch_new_instance()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:23: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(10, (1, 1), kernel_regularizer=<keras.reg...)`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:27: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(16, (3, 3), kernel_regularizer=<keras.reg...)`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(16, (3, 3), kernel_regularizer=<keras.reg...)`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.p

In [4]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 10)        100       
_________________________________________________________________
batch_normalization_1 (Batch (None, 26, 26, 10)        40        
_________________________________________________________________
activation_1 (Activation)    (None, 26, 26, 10)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 24, 24, 16)        1456      
_________________________________________________________________
batch_normalization_2 (Batch (None, 24, 24, 16)        64        
_________________________________________________________________
activation_2 (Activation)    (None, 24, 24, 16)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 22, 22, 16)        2320      
__________

In [0]:
def scheduler(epoch, lr):
  return round(0.007 * 1/(1 + 0.121 * epoch), 10)

In [0]:
from keras import optimizers
from keras.callbacks import ModelCheckpoint, LearningRateScheduler

In [0]:
adam = optimizers.Adam(lr=0.007)

In [0]:
# compile model
model.compile(optimizer=adam, loss='categorical_crossentropy', metrics=['accuracy'])

In [0]:
filepath="/content/drive/My Drive/EVA-Assignment-5-weights/EVA-Assignment-5-weights.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_acc', save_best_only=True,verbose=1,save_weights_only=True,period=1,mode='max')
callbacks_list = [checkpoint]

In [10]:
# fit model with generator
model.fit_generator(train_iterator, steps_per_epoch=512, epochs=40, verbose=1,callbacks=[checkpoint,LearningRateScheduler(scheduler)],validation_data=test_iterator,validation_steps=512)
# evaluate model

Instructions for updating:
Use tf.cast instead.
Epoch 1/40
512/512 [==============================] - 27s 52ms/step - loss: 0.4337 - acc: 0.9539 - val_loss: 0.3453 - val_acc: 0.9533

Epoch 00001: val_acc improved from -inf to 0.95335, saving model to /content/drive/My Drive/EVA-Assignment-5-weights/EVA-Assignment-5-weights.hdf5
Epoch 2/40
512/512 [==============================] - 21s 42ms/step - loss: 0.2185 - acc: 0.9768 - val_loss: 0.6061 - val_acc: 0.8439

Epoch 00002: val_acc did not improve from 0.95335
Epoch 3/40
512/512 [==============================] - 21s 42ms/step - loss: 0.1921 - acc: 0.9785 - val_loss: 0.6729 - val_acc: 0.8197

Epoch 00003: val_acc did not improve from 0.95335
Epoch 4/40
512/512 [==============================] - 21s 42ms/step - loss: 0.1755 - acc: 0.9797 - val_loss: 0.2755 - val_acc: 0.9489

Epoch 00004: val_acc did not improve from 0.95335
Epoch 5/40
512/512 [==============================] - 21s 42ms/step - loss: 0.1631 - acc: 0.9806 - val_loss: 0.2415

In [0]:
model.load_weights("/content/drive/My Drive/EVA-Assignment-5-weights/EVA-Assignment-5-weights.hdf5") ## Load the weights that gave highest validation accuracy

In [12]:
stats = model.evaluate_generator(test_iterator, steps=512,  max_queue_size=10, workers=1, use_multiprocessing=False, verbose=1) ## get loass, accuracy 

512/512 [==============================] - 5s 10ms/step


In [13]:
print("Loss, Accuracy = ", stats)

Loss, Accuracy =  [0.06816613846594333, 0.9908996499175247]


In [0]:
import pandas as pd
import numpy

In [0]:
predicted = model.predict_generator(datagen.flow(testX, testY, batch_size=512, shuffle = False), steps = numpy.ceil(testX.shape[0]/512)) ## predict using model

In [0]:
predicted = numpy.argmax(predicted, axis = 1) ## create a 1-d array of predicted test values

In [17]:
predicted

array([7, 2, 1, ..., 4, 5, 6])

In [0]:
actual = numpy.argmax(testY, axis = 1) ## create 1-d arra of original test values

In [19]:
actual

array([7, 2, 1, ..., 4, 5, 6])

In [0]:
from sklearn.metrics import confusion_matrix

In [0]:
cm = confusion_matrix(actual, predicted) ## create confusion matrix

In [22]:
cm

array([[ 979,    0,    0,    0,    0,    0,    0,    1,    0,    0],
       [   0, 1130,    0,    3,    0,    1,    1,    0,    0,    0],
       [   1,    2, 1023,    0,    0,    0,    2,    4,    0,    0],
       [   0,    0,    0, 1010,    0,    0,    0,    0,    0,    0],
       [   1,    2,    1,    0,  968,    0,    0,    2,    0,    8],
       [   0,    0,    0,    7,    0,  881,    2,    1,    0,    1],
       [   8,    3,    1,    0,    0,    0,  946,    0,    0,    0],
       [   0,    8,    2,    1,    0,    0,    0, 1017,    0,    0],
       [   3,    1,    2,    2,    0,    0,    0,    2,  957,    7],
       [   3,    1,    0,    0,    2,    3,    0,    2,    0,  998]])

In [0]:
full_df = pd.DataFrame(data = {'predicted': predicted, 'actual': actual}) ## create a dataframe 

In [24]:
full_df.shape

(10000, 2)

In [25]:
full_df.dtypes

predicted    int64
actual       int64
dtype: object

In [26]:
full_df

predicted  actual
0             7       7
1             2       2
2             1       1
3             0       0
4             4       4
5             1       1
6             4       4
7             9       9
8             5       5
9             9       9
10            0       0
11            6       6
12            9       9
13            0       0
14            1       1
15            5       5
16            9       9
17            7       7
18            3       3
19            4       4
20            9       9
21            6       6
22            6       6
23            5       5
24            4       4
25            0       0
26            7       7
27            4       4
28            0       0
29            1       1
...         ...     ...
9970          5       5
9971          2       2
9972          4       4
9973          9       9
9974          4       4
9975          3       3
9976          6       6
9977          4       4
9978          1       1
9979          7       7
9980          2       2
9981          6       6
9982          5       5
9983          0       0
9984          1       1
9985          2       2
9986          3       3
9987          4       4
9988          5       5
9989          6       6
9990          7       7
9991          8       8
9992          9       9
9993          0       0
9994          1       1
9995          2       2
9996          3       3
9997          4       4
9998          5       5
9999          6       6

[10000 rows x 2 columns]

In [0]:
misclassified = full_df[(full_df.predicted != full_df.actual)] ## dataframe that contains misclassified images

In [29]:
misclassified ## list misclassified images

predicted  actual
115           9       4
259           0       6
321           7       2
445           0       6
495           0       8
543           2       8
582           2       8
646           6       2
659           1       2
674           3       5
900           3       1
916           2       4
947           9       8
956           3       1
965           0       6
1014          0       6
1178          0       4
1232          4       9
1247          5       9
1260          1       7
1299          7       5
1444          0       6
1500          3       7
1527          5       1
1530          7       8
1737          3       5
1790          7       2
1878          3       8
1901          4       9
2035          3       5
...         ...     ...
4639          9       8
4731          7       8
4837          1       7
4860          9       4
4874          0       9
4886          1       7
4978          9       8
5833          9       5
5937          3       5
6028          3       5
6555          9       8
6558          2       6
6571          7       9
6576          1       7
6597          7       0
6625          1       8
6740          0       9
6755          9       8
6906          6       2
7432          1       7
7514          0       8
8092          1       4
8095          1       4
8527          9       4
9620          1       9
9669          7       4
9679          1       6
9692          7       9
9729          6       5
9839          7       2

[91 rows x 2 columns]

In [30]:
misclassified.values

array([[9, 4],
       [0, 6],
       [7, 2],
       [0, 6],
       [0, 8],
       [2, 8],
       [2, 8],
       [6, 2],
       [1, 2],
       [3, 5],
       [3, 1],
       [2, 4],
       [9, 8],
       [3, 1],
       [0, 6],
       [0, 6],
       [0, 4],
       [4, 9],
       [5, 9],
       [1, 7],
       [7, 5],
       [0, 6],
       [3, 7],
       [5, 1],
       [7, 8],
       [3, 5],
       [7, 2],
       [3, 8],
       [4, 9],
       [3, 5],
       [6, 5],
       [3, 5],
       [0, 6],
       [9, 4],
       [1, 6],
       [9, 8],
       [3, 1],
       [0, 9],
       [9, 4],
       [0, 2],
       [1, 2],
       [3, 5],
       [1, 6],
       [9, 4],
       [7, 4],
       [0, 8],
       [9, 4],
       [5, 9],
       [0, 6],
       [1, 7],
       [9, 8],
       [0, 6],
       [6, 1],
       [2, 7],
       [2, 7],
       [1, 7],
       [3, 8],
       [1, 7],
       [7, 2],
       [5, 9],
       [9, 4],
       [9, 8],
       [7, 8],
       [1, 7],
       [9, 4],
       [0, 9],
       [1,

In [31]:
misclassified.actual.head(25)

115     4
259     6
321     2
445     6
495     8
543     8
582     8
646     2
659     2
674     5
900     1
916     4
947     8
956     1
965     6
1014    6
1178    4
1232    9
1247    9
1260    7
1299    5
1444    6
1500    7
1527    1
1530    8
Name: actual, dtype: int64

In [32]:
misclassified.shape

(91, 2)

In [0]:
proper_classified = full_df[(full_df.predicted == full_df.actual)]

In [35]:
proper_classified

predicted  actual
0             7       7
1             2       2
2             1       1
3             0       0
4             4       4
5             1       1
6             4       4
7             9       9
8             5       5
9             9       9
10            0       0
11            6       6
12            9       9
13            0       0
14            1       1
15            5       5
16            9       9
17            7       7
18            3       3
19            4       4
20            9       9
21            6       6
22            6       6
23            5       5
24            4       4
25            0       0
26            7       7
27            4       4
28            0       0
29            1       1
...         ...     ...
9970          5       5
9971          2       2
9972          4       4
9973          9       9
9974          4       4
9975          3       3
9976          6       6
9977          4       4
9978          1       1
9979          7       7
9980          2       2
9981          6       6
9982          5       5
9983          0       0
9984          1       1
9985          2       2
9986          3       3
9987          4       4
9988          5       5
9989          6       6
9990          7       7
9991          8       8
9992          9       9
9993          0       0
9994          1       1
9995          2       2
9996          3       3
9997          4       4
9998          5       5
9999          6       6

[9909 rows x 2 columns]